// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: MultiPage_Project

#ifndef _MULTIPAGE_PROJECT_UI_H
#define _MULTIPAGE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void Fan1_Animation(lv_obj_t * TargetObject, int delay);
void Fan2_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_HourHand;
extern lv_obj_t * ui_MinuteHand;
extern lv_obj_t * ui_SecondHand;
void ui_event_TopButton(lv_event_t * e);
extern lv_obj_t * ui_TopButton;
extern lv_obj_t * ui_MiddleButton;
extern lv_obj_t * ui_BottomButton;
extern lv_obj_t * ui_Panel1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_TopButton1;
void ui_event_MiddleButton1(lv_event_t * e);
extern lv_obj_t * ui_MiddleButton1;
extern lv_obj_t * ui_ButtomButton1;
void ui_event_TopSwitch(lv_event_t * e);
extern lv_obj_t * ui_TopSwitch;
extern lv_obj_t * ui_TopFanLabel;
void ui_event_BottomSwitch(lv_event_t * e);
extern lv_obj_t * ui_BottomSwitch;
extern lv_obj_t * ui_BottomFanLabel;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_LedButton;
extern lv_obj_t * ui_Fan1;
extern lv_obj_t * ui_Fan2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_GreenLed;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_watchface3_png);    // assets/watchface3.png
LV_IMG_DECLARE(ui_img_partly_cloudy_png);    // assets/partly_cloudy.png
LV_IMG_DECLARE(ui_img_clockwise_hour_png);    // assets/clockwise_hour.png
LV_IMG_DECLARE(ui_img_clockwise_min_png);    // assets/clockwise_min.png
LV_IMG_DECLARE(ui_img_clockwise_sec_png);    // assets/clockwise_sec.png
LV_IMG_DECLARE(ui_img_texture_background_png);    // assets/Texture_Background.png
LV_IMG_DECLARE(ui_img_fan_png);    // assets/fan.png
LV_IMG_DECLARE(ui_img_sun_2_png);    // assets/Sun_2.png
LV_IMG_DECLARE(ui_img_watchface2_png);    // assets/watchface2.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
